
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class addScore extends javax.swing.JFrame {

    /**
     * Creates new form Addscore
     */
    course c = new course();
    student std = new student();
    score sc = new score();
     DefaultTableModel model;
    public addScore() {
        initComponents();
        c.fillCourseJtable(jComboBox1);
        std.fillStudentJtable(jTable1, "");
        
        HideColumn(6);
        HideColumn(5);
        HideColumn(4);
        HideColumn(3);
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.red);
        jTable1.setSelectionBackground(Color.PINK);
    }
//     public addScore() {
//    initComponents();
//    
//    try {
//        c.fillCourseJtable(jComboBox1);
//    } catch (Exception e) {
//        System.out.println("Lỗi khi gọi fillCourseJtable:");
//        e.printStackTrace();
//    }
//
//    try {
//        std.fillStudentJtable(jTable1, "");
//    } catch (Exception e) {
//        System.out.println("Lỗi khi gọi fillStudentJtable:");
//        e.printStackTrace();
//    }
//
//    HideColumn(6);
//    HideColumn(5);
//    HideColumn(4);
//    HideColumn(3);
//    
//    model = (DefaultTableModel) jTable1.getModel();
//    jTable1.setRowHeight(40);
//    jTable1.setShowGrid(true);
//    jTable1.setGridColor(Color.red);
//    jTable1.setSelectionBackground(Color.PINK);
//}

  private void HideColumn(int colIndex){
  TableColumn col = jTable1.getColumnModel().getColumn(colIndex);
  col.setMaxWidth(0);
  col.setMinWidth(0);
  col.setPreferredWidth(0);
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonadd = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_score = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField_des = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Score");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Course :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Score:");

        jButtonadd.setBackground(new java.awt.Color(102, 255, 102));
        jButtonadd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonadd.setText("ADD");
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });

        jButtoncancel.setBackground(new java.awt.Color(255, 0, 0));
        jButtoncancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtoncancel.setText("Cancel");
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Student ID:");

        jTextField_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIRST_NAME", "LAST_NAME", "SEX", "BIRTHDATE", "PHONE", "ADDRESS"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTextField_score.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Description:");

        jTextField_des.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_score, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                        .addComponent(jTextField_des, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jButtoncancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_score, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_des, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtoncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(470, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
       
        int stdId = Integer.valueOf(jTextField_id.getText());
         int   crsId = Integer.valueOf(c.getCourseId(jComboBox1.getSelectedItem().toString()));
       double scr = Double.valueOf(jTextField_score.getText());
    System.out.println(crsId);
sc.insertUpdateDeleteStudent('i', stdId, crsId ,scr, jTextField_des.getText());
        

//     if(!c.isCourseExist(jTextField_id.getText())){
        //          int id = Integer.valueOf(jSpinner1.getValue().toString());
        //           String subject = jTextField_label.getText();
        //        int hours = Integer.valueOf(jSpinner1.getValue().toString());
        //        c.insertUpdateDeleteStudent('i', null, subject, hours);
        //
        //        manageCou.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Subject", "Hours"}));
        //        c.fillCourseJtable(manageCou.jTable1);
        //        Login.jLabel3_mon.setText("COURSE COUNT = " + Integer.toString(Myfunction.countData("course")));
        //        JOptionPane.showMessageDialog(null, "Course Edited");
        //        }else{
        //        JOptionPane.showMessageDialog(null, "Course Already Exist");
        //        }

//        Addmon addmon =new Addmon();
//        addmon.setVisible(true);
//        addmon.pack();
//        addmon.setLocationRelativeTo(null);
//        addmon.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //        if(!c.isCourseExist(jTextField_label.getText())){
        //            String subject = jTextField_label.getText();
        //            int hours = Integer.valueOf(jSpinner1.getValue().toString());
        //            c.insertUpdateDeleteStudent('i', null, subject, hours);
        //            Login.jLabel3_mon.setText("COURSE COUNT = " + Integer.toString(Myfunction.countData("course")));
        //        }else{
        //            JOptionPane.showMessageDialog(null, "Course Already Exist");
        //        }
        //        String subject = jTextField_label.getText();
        //        int hours = Integer.valueOf(jSpinner1.getValue().toString());
        //        c.insertUpdateDeleteStudent('i', null, subject, hours);
        // TODO add your handling code here:
        //        String fname = jTextField_ten.getText();
        //        String lname = jTextField_ho.getText();
        //        String phone = jTextFieldphone.getText();
        //        String address = jTextArea1.getText();
        //        String sex = "Male";
        //        if(jRadioButtonfemale.isSelected()){
        //            sex = "Female";
        //        }
        //
        //        if(verifText()){
        //            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //            String bdate = dateFormat.format(jDateChooser.getDate());
        //            student stu = new student();
        //            stu.insertUpdateDeleteStudent('i', null, fname, lname, sex, bdate, phone, address);
        //            Login.jLabel_count.setText("STUDENT COUNT = " + Integer.toString(Myfunction.countData("student")));
        //        }
        // SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        // String bdate = dateFormat.format(jDateChooser.getDate());
        // student stu = new student();
        //        // stu.insertUpdateDeleteStudent('i', null, fname, lname, sex, bdate, phone, address);
        //        Addstu adds =new Addstu();
        //        adds.setVisible(true);
        //        adds.pack();
        //        adds.setLocationRelativeTo(null);
        //        adds.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
       this.dispose();
        
//        try {
        //        int id = Integer.parseInt(jTextField_id.getText().trim());
        //        c.insertUpdateDeleteStudent('d', id, null, null);
        //
        //        manageCou.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Subject", "Hours"}));
        //        c.fillCourseJtable(manageCou.jTable1);
        //    } catch (NumberFormatException e) {
        //        JOptionPane.showMessageDialog(null, "ID phải là số nguyên hợp lệ.");
        //    }
//        if(!jTextField_id.getText().equals("")){
//            int id = Integer.valueOf(jTextField_id.getText());
//            c.insertUpdateDeleteStudent('d', id, null, null);
//            manageCou.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Subject", "Hours"}));
//            c.fillCourseJtable(manageCou.jTable1);
//            jTextField_id.setText("");
//            jTextField_label.setText("");
//            jSpinner1.setValue(1);
//        }
    }//GEN-LAST:event_jButtoncancelActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     int   rowIndex =jTable1.getSelectedRow();
    jTextField_id.setText(jTable1.getValueAt(rowIndex, 0).toString());
// TODO add your handling code here:
//        rowIndex =jTable1.getSelectedRow();
//
//        if(model.getValueAt(rowIndex,3).toString().equals("Male")){
//            jRadioButtonmale.setSelected(true);
//            jRadioButtonfemale.setSelected(false);
//        }else{
//            jRadioButtonfemale.setSelected(true);
//            jRadioButtonmale.setSelected(false);
//        }
//
//        jTextField_id1.setText(model.getValueAt(rowIndex, 0).toString());
//        jTextField_ten.setText(model.getValueAt(rowIndex, 1).toString());
//        jTextField_ho.setText(model.getValueAt(rowIndex, 2).toString());
//        jTextFieldphone.setText(model.getValueAt(rowIndex, 5).toString());
//        jTextArea1.setText(model.getValueAt(rowIndex, 6).toString());
//
//        Date bdate;
//        try {
//            bdate =new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
//            jDateChooser.setDate(bdate);
//
//        } catch (ParseException ex) {
//            Logger.getLogger(manageStu.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
//        if(evt.getKeyCode()== KeyEvent.VK_DOWN || evt.getKeyCode()== KeyEvent.VK_UP)  {
//            rowIndex = jTable1.getSelectedRow();
//            jTextField_id1.setText(model.getValueAt(rowIndex, 0).toString());
//            jTextField_ten.setText(model.getValueAt(rowIndex, 1).toString());
//            jTextField_ho.setText(model.getValueAt(rowIndex, 2).toString());
//            jTextFieldphone.setText(model.getValueAt(rowIndex, 5).toString());
//            jTextArea1.setText(model.getValueAt(rowIndex, 6).toString());
//
//            if(model.getValueAt(rowIndex,3).toString().equals("Male")){
//                jRadioButtonmale.setSelected(true);
//                jRadioButtonfemale.setSelected(false);
//            }else{
//                jRadioButtonfemale.setSelected(true);
//                jRadioButtonmale.setSelected(false);
//            }
//            Date bdate;
//            try {
//                bdate =new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
//                jDateChooser.setDate(bdate);
//
//            } catch (ParseException ex) {
//                Logger.getLogger(manageStu.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }

    }//GEN-LAST:event_jTable1KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtoncancel;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_des;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_score;
    // End of variables declaration//GEN-END:variables
}
