

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class editscore extends javax.swing.JFrame {

    DefaultTableModel model;
    
    score sc = new score();
    public editscore() {
        initComponents();
        sc.fillScoreJtable(jTable1);
         model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.red);
        jTable1.setSelectionBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonedit = new javax.swing.JButton();
        jButtonremove = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_score = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_des = new javax.swing.JTextField();
        jTextField_course = new javax.swing.JTextField();
        jButtonadd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Edit / Delete Score");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Course :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Score:");

        jButtonedit.setBackground(new java.awt.Color(255, 0, 255));
        jButtonedit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonedit.setText("Edit");
        jButtonedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditActionPerformed(evt);
            }
        });

        jButtonremove.setBackground(new java.awt.Color(255, 0, 0));
        jButtonremove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonremove.setText("Remove");
        jButtonremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonremoveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Student ID:");

        jTextField_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_Id", "Course_Id", "Score", "Description"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTextField_score.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Description:");

        jTextField_des.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_course.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonadd.setBackground(new java.awt.Color(102, 255, 102));
        jButtonadd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonadd.setText("Add");
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jButtonremove))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_des, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_score, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_course, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButtonedit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_course, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_score, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_des, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonedit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonremove, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditActionPerformed
   int sid = Integer.valueOf(jTextField_id.getText());
   int cid = Integer.valueOf(jTextField_course.getText());     
      double scr    = Double.valueOf(jTextField_score.getText());
      String ds =  jTextField_des.getText();
      
      sc.insertUpdateDeleteStudent('u', sid, cid, scr, ds);
      jTable1.setModel(new DefaultTableModel(null, new Object[]{"Student_Id", "Course_Id", "Score", "Description"}));
      sc.fillScoreJtable(jTable1);
//        int stdId = Integer.valueOf(jTextField_id.getText());
//        int crsId = Integer.valueOf( c.getCourseId(jComboBox1.getSelectedItem().toString()));
//        double scr = Double.valueOf(jTextField_score.getText());
//        System.out.println(crsId);
//        sc.insertUpdateDeleteStudent('i', stdId, crsId ,scr, jTextField_des.getText());

        //     if(!c.isCourseExist(jTextField_id.getText())){
            //          int id = Integer.valueOf(jSpinner1.getValue().toString());
            //           String subject = jTextField_label.getText();
            //        int hours = Integer.valueOf(jSpinner1.getValue().toString());
            //        c.insertUpdateDeleteStudent('i', null, subject, hours);
            //
            //        manageCou.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Subject", "Hours"}));
            //        c.fillCourseJtable(manageCou.jTable1);
            //        Login.jLabel3_mon.setText("COURSE COUNT = " + Integer.toString(Myfunction.countData("course")));
            //        JOptionPane.showMessageDialog(null, "Course Edited");
            //        }else{
            //        JOptionPane.showMessageDialog(null, "Course Already Exist");
            //        }

        //        Addmon addmon =new Addmon();
        //        addmon.setVisible(true);
        //        addmon.pack();
        //        addmon.setLocationRelativeTo(null);
        //        addmon.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //        if(!c.isCourseExist(jTextField_label.getText())){
            //            String subject = jTextField_label.getText();
            //            int hours = Integer.valueOf(jSpinner1.getValue().toString());
            //            c.insertUpdateDeleteStudent('i', null, subject, hours);
            //            Login.jLabel3_mon.setText("COURSE COUNT = " + Integer.toString(Myfunction.countData("course")));
            //        }else{
            //            JOptionPane.showMessageDialog(null, "Course Already Exist");
            //        }
        //        String subject = jTextField_label.getText();
        //        int hours = Integer.valueOf(jSpinner1.getValue().toString());
        //        c.insertUpdateDeleteStudent('i', null, subject, hours);
        // TODO add your handling code here:
        //        String fname = jTextField_ten.getText();
        //        String lname = jTextField_ho.getText();
        //        String phone = jTextFieldphone.getText();
        //        String address = jTextArea1.getText();
        //        String sex = "Male";
        //        if(jRadioButtonfemale.isSelected()){
            //            sex = "Female";
            //        }
        //
        //        if(verifText()){
            //            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            //            String bdate = dateFormat.format(jDateChooser.getDate());
            //            student stu = new student();
            //            stu.insertUpdateDeleteStudent('i', null, fname, lname, sex, bdate, phone, address);
            //            Login.jLabel_count.setText("STUDENT COUNT = " + Integer.toString(Myfunction.countData("student")));
            //        }
        // SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        // String bdate = dateFormat.format(jDateChooser.getDate());
        // student stu = new student();
        //        // stu.insertUpdateDeleteStudent('i', null, fname, lname, sex, bdate, phone, address);
        //        Addstu adds =new Addstu();
        //        adds.setVisible(true);
        //        adds.pack();
        //        adds.setLocationRelativeTo(null);
        //        adds.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtoneditActionPerformed

    private void jButtonremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonremoveActionPerformed
  
  int sid = Integer.valueOf(jTextField_id.getText());
   int cid = Integer.valueOf(jTextField_course.getText());
   sc.insertUpdateDeleteStudent('d', sid, cid, null, null);
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Student_Id", "Course_Id", "Score", "Description"}));
      sc.fillScoreJtable(jTable1);
        //        try {
            //        int id = Integer.parseInt(jTextField_id.getText().trim());
            //        c.insertUpdateDeleteStudent('d', id, null, null);
            //
            //        manageCou.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Subject", "Hours"}));
            //        c.fillCourseJtable(manageCou.jTable1);
            //    } catch (NumberFormatException e) {
            //        JOptionPane.showMessageDialog(null, "ID phải là số nguyên hợp lệ.");
            //    }
        //        if(!jTextField_id.getText().equals("")){
            //            int id = Integer.valueOf(jTextField_id.getText());
            //            c.insertUpdateDeleteStudent('d', id, null, null);
            //            manageCou.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Subject", "Hours"}));
            //            c.fillCourseJtable(manageCou.jTable1);
            //            jTextField_id.setText("");
            //            jTextField_label.setText("");
            //            jSpinner1.setValue(1);
            //        }
    }//GEN-LAST:event_jButtonremoveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int   rowIndex =jTable1.getSelectedRow();
        jTextField_id.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextField_course.setText(jTable1.getValueAt(rowIndex, 1).toString());
         jTextField_score.setText(jTable1.getValueAt(rowIndex, 2).toString());
          jTextField_des.setText(jTable1.getValueAt(rowIndex, 3).toString());
        // TODO add your handling code here:
        //        rowIndex =jTable1.getSelectedRow();
        //
        //        if(model.getValueAt(rowIndex,3).toString().equals("Male")){
            //            jRadioButtonmale.setSelected(true);
            //            jRadioButtonfemale.setSelected(false);
            //        }else{
            //            jRadioButtonfemale.setSelected(true);
            //            jRadioButtonmale.setSelected(false);
            //        }
        //
        //        jTextField_id1.setText(model.getValueAt(rowIndex, 0).toString());
        //        jTextField_ten.setText(model.getValueAt(rowIndex, 1).toString());
        //        jTextField_ho.setText(model.getValueAt(rowIndex, 2).toString());
        //        jTextFieldphone.setText(model.getValueAt(rowIndex, 5).toString());
        //        jTextArea1.setText(model.getValueAt(rowIndex, 6).toString());
        //
        //        Date bdate;
        //        try {
            //            bdate =new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            //            jDateChooser.setDate(bdate);
            //
            //        } catch (ParseException ex) {
            //            Logger.getLogger(manageStu.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        //        if(evt.getKeyCode()== KeyEvent.VK_DOWN || evt.getKeyCode()== KeyEvent.VK_UP)  {
            //            rowIndex = jTable1.getSelectedRow();
            //            jTextField_id1.setText(model.getValueAt(rowIndex, 0).toString());
            //            jTextField_ten.setText(model.getValueAt(rowIndex, 1).toString());
            //            jTextField_ho.setText(model.getValueAt(rowIndex, 2).toString());
            //            jTextFieldphone.setText(model.getValueAt(rowIndex, 5).toString());
            //            jTextArea1.setText(model.getValueAt(rowIndex, 6).toString());
            //
            //            if(model.getValueAt(rowIndex,3).toString().equals("Male")){
                //                jRadioButtonmale.setSelected(true);
                //                jRadioButtonfemale.setSelected(false);
                //            }else{
                //                jRadioButtonfemale.setSelected(true);
                //                jRadioButtonmale.setSelected(false);
                //            }
            //            Date bdate;
            //            try {
                //                bdate =new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
                //                jDateChooser.setDate(bdate);
                //
                //            } catch (ParseException ex) {
                //                Logger.getLogger(manageStu.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
    themDiem addscro111 =  new themDiem();
    addscro111.setVisible(true);
    addscro111.pack();
    addscro111.setLocationRelativeTo(null);
    addscro111.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editscore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtonedit;
    private javax.swing.JButton jButtonremove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_course;
    private javax.swing.JTextField jTextField_des;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_score;
    // End of variables declaration//GEN-END:variables
}
